version: 2
jobs:
    build:
        working_directory: /go/src/github.com/kinvolk/habitat-service-broker
        docker:
            - image: circleci/golang:1.10
        steps:
            - checkout
            - run:
                name: Build and run tests
                command: |
                    make build test
