apiVersion: v1
kind: Namespace
metadata:
  name: redis-habitat
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: redis-habitat
  namespace: redis-habitat
spec:
  clusterServiceClassExternalName: redis-habitat
  clusterServicePlanExternalName: default
